Traceback (most recent call last):
  File "train.py", line 3, in <module>
    import torchvision
  File "/dataset/lei/anaconda3/envs/siamese-pytorch-pillow-9.2.0/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/dataset/lei/anaconda3/envs/siamese-pytorch-pillow-9.2.0/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/dataset/lei/anaconda3/envs/siamese-pytorch-pillow-9.2.0/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/dataset/lei/anaconda3/envs/siamese-pytorch-pillow-9.2.0/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/dataset/lei/anaconda3/envs/siamese-pytorch-pillow-9.2.0/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/dataset/lei/anaconda3/envs/siamese-pytorch-pillow-9.2.0/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/dataset/lei/anaconda3/envs/siamese-pytorch-pillow-9.2.0/lib/python3.7/site-packages/PIL/__init__.py)
