Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from datasets.main import load_dataset
  File "/home/lei/compatibility_analysis/pytorch/1.1/Deep-SAD-PyTorch/src/datasets/__init__.py", line 1, in <module>
    from .main import load_dataset
  File "/home/lei/compatibility_analysis/pytorch/1.1/Deep-SAD-PyTorch/src/datasets/main.py", line 2, in <module>
    from .fmnist import FashionMNIST_Dataset
  File "/home/lei/compatibility_analysis/pytorch/1.1/Deep-SAD-PyTorch/src/datasets/fmnist.py", line 3, in <module>
    from torchvision.datasets import FashionMNIST
ImportError: cannot import name 'FashionMNIST' from 'torchvision.datasets' (/home/lei/anaconda3/envs/py37/lib/python3.7/site-packages/torchvision/datasets/__init__.py)
