Traceback (most recent call last):
  File "/home/lei/anaconda3/envs/py37-3/lib/python3.7/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/home/lei/anaconda3/envs/py37-3/lib/python3.7/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: libnvrtc.so.11.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 11, in <module>
    import sepconv # the custom separable convolution layer
  File "/home/lei/compatibility_analysis/pytorch/1.7/sepconv-slomo/sepconv.py", line 4, in <module>
    import cupy
  File "/home/lei/anaconda3/envs/py37-3/lib/python3.7/site-packages/cupy/__init__.py", line 27, in <module>
    ''') from exc
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libnvrtc.so.11.0: cannot open shared object file: No such file or directory
================================================================

